"""Build Scenario service — orchestrates multi-source ontology builds."""

from __future__ import annotations

import uuid
from pathlib import Path

from .models import (
    BuildScenarioDef,
    BuildStageDef,
    BuildPlan,
    BuildPlanStage,
    BuildPlanSummary,
    BuildPlanValidationSummary,
)

_SAMPLE_DIR = Path(__file__).resolve().parent.parent.parent / "sample-data" / "pet-food"

# Stage definitions for Pet Food full build
_PET_FOOD_STAGES = [
    BuildStageDef(
        stage_id="reference_objects",
        title="Reference Objects",
        description="Brand, Species, LifeStage — foundational entities",
        object_types=["Brand", "Species", "LifeStage"],
        link_types=[],
        order=1,
    ),
    BuildStageDef(
        stage_id="core_objects",
        title="Core Objects",
        description="PetFoodProduct, Ingredient, RiskRule — main ontology entities",
        object_types=["PetFoodProduct", "Ingredient", "RiskRule"],
        link_types=[],
        order=2,
    ),
    BuildStageDef(
        stage_id="relationships",
        title="Relationships",
        description="MADE_BY, CONTAINS, TARGETS_SPECIES, SUITABLE_FOR — entity connections",
        object_types=[],
        link_types=["MADE_BY", "CONTAINS", "TARGETS_SPECIES", "SUITABLE_FOR"],
        order=3,
    ),
    BuildStageDef(
        stage_id="rule_evidence",
        title="Rule-Generated Evidence",
        description="TRIGGERS_RISK — evidence edges generated by rule engine",
        object_types=[],
        link_types=["TRIGGERS_RISK"],
        order=4,
    ),
]

_SCENARIOS: dict[str, BuildScenarioDef] = {
    "pet_food_full_build": BuildScenarioDef(
        id="pet_food_full_build",
        name="Build Full Pet Food Ontology",
        description="Start from multiple sample datasets and generate a complete reviewable ontology build plan.",
        sources=[
            "pet_food_products.csv",
            "pet_food_ingredients.csv",
            "product_ingredients.csv",
            "risk_rules.csv",
        ],
        stages=_PET_FOOD_STAGES,
    ),
}

# In-memory build plan storage
_build_plans: dict[str, BuildPlan] = {}


class BuildScenarioService:

    # ---------- scenario definitions ----------

    @staticmethod
    def list_scenarios() -> list[BuildScenarioDef]:
        return list(_SCENARIOS.values())

    @staticmethod
    def get_scenario(scenario_id: str) -> BuildScenarioDef | None:
        return _SCENARIOS.get(scenario_id)

    # ---------- build plan creation ----------

    @staticmethod
    def create_build_plan(scenario_id: str) -> BuildPlan:
        scenario = _SCENARIOS.get(scenario_id)
        if not scenario:
            raise ValueError(f"Unknown scenario: {scenario_id}")

        if scenario_id == "pet_food_full_build":
            return _create_pet_food_build_plan(scenario)

        raise ValueError(f"No implementation for scenario: {scenario_id}")

    # ---------- build plan storage ----------

    @staticmethod
    def get_build_plan(plan_id: str) -> BuildPlan | None:
        return _build_plans.get(plan_id)

    @staticmethod
    def list_build_plans() -> list[BuildPlan]:
        return sorted(_build_plans.values(), key=lambda p: p.created_at, reverse=True)

    @staticmethod
    def save_build_plan(plan: BuildPlan):
        _build_plans[plan.id] = plan

    # ---------- submit to review ----------

    @staticmethod
    def submit_to_review(plan_id: str) -> dict:
        from review_queue.import_plan_adapter import create_review_batch_from_import_plan
        from review_queue.storage import upsert_batch, load_items, save_items
        from data_pipeline.models import ImportPlan, ImportPlanSummary

        plan = _build_plans.get(plan_id)
        if not plan:
            raise ValueError(f"Build plan not found: {plan_id}")
        if plan.submitted_to_review:
            raise ValueError(f"Build plan already submitted to review")

        # Flatten all stages into a single ImportPlan for review queue compatibility
        all_objects = []
        all_links = []
        all_warnings = []

        for stage in sorted(plan.stages, key=lambda s: s.order):
            for obj in stage.candidate_objects:
                obj["_stage_id"] = stage.stage_id
                obj["_stage_order"] = stage.order
                all_objects.append(obj)
            for link in stage.candidate_links:
                link["_stage_id"] = stage.stage_id
                link["_stage_order"] = stage.order
                all_links.append(link)
            all_warnings.extend(stage.validation_warnings)

        # Build a synthetic ImportPlan
        issues = [{"level": "warning", "message": w} for w in all_warnings]

        import_plan = ImportPlan(
            plan_id=f"build-{plan.id}",
            domain="pet_food",
            candidate_objects=all_objects,
            candidate_links=all_links,
            validation_issues=issues,
            summary=ImportPlanSummary(
                new_objects=len(all_objects),
                new_links=len(all_links),
                validation_errors=plan.summary.total_validation_errors,
                validation_warnings=plan.summary.total_validation_warnings,
            ),
            status="validated" if plan.summary.total_validation_errors == 0 else "has_errors",
        )

        result = create_review_batch_from_import_plan(import_plan)

        # Persist batch and items directly
        upsert_batch(result.batch)
        all_items = load_items()
        all_items.extend(result.items)
        save_items(all_items)

        plan.submitted_to_review = True
        plan.review_batch_id = result.batch.id
        plan.status = "submitted_to_review"
        _build_plans[plan_id] = plan

        return {
            "build_plan_id": plan.id,
            "batch_id": result.batch.id,
            "items_created": len(result.items),
            "stages": len(plan.stages),
        }


def _create_pet_food_build_plan(scenario: BuildScenarioDef) -> BuildPlan:
    """Create a build plan using the Pet Food transformer."""
    from domain.petfood_transformer import transform
    from rule_engine import RuleEngine
    from ontology_registry import OntologyRegistry
    from constraint_validator import validate_payload

    if not _SAMPLE_DIR.exists():
        raise ValueError("Sample data directory not found")

    # Transform all CSVs into a full graph payload
    payload = transform(_SAMPLE_DIR)
    registry = OntologyRegistry("pet_food")
    engine = RuleEngine(registry)
    payload = engine.apply_rules(payload)

    # Validate
    vr = validate_payload(registry, payload)
    errors = [e for e in vr.get("errors", [])]
    warnings = [w for w in vr.get("warnings", [])]

    # Organize nodes by type (transformer uses 'label' field)
    nodes_by_type: dict[str, list[dict]] = {}
    for node in payload.get("nodes", []):
        obj_type = node.get("label", node.get("object_type", node.get("type", "Unknown")))
        nodes_by_type.setdefault(obj_type, []).append(node)

    # Organize edges by type (transformer uses 'type' field)
    edges_by_type: dict[str, list[dict]] = {}
    for edge in payload.get("edges", []):
        link_type = edge.get("type", edge.get("edge_type", "UNKNOWN"))
        edges_by_type.setdefault(link_type, []).append(edge)

    # Build stages
    stages = []
    for stage_def in scenario.stages:
        stage_objects = []
        for obj_type in stage_def.object_types:
            for node in nodes_by_type.get(obj_type, []):
                props = node.get("properties", {})
                if not props:
                    props = {k: v for k, v in node.items() if k not in ("id", "label", "object_type", "type")}
                stage_objects.append({
                    "id": node.get("id", ""),
                    "type": obj_type,
                    "object_type": obj_type,
                    "properties": props,
                })

        stage_links = []
        for link_type in stage_def.link_types:
            for edge in edges_by_type.get(link_type, []):
                stage_links.append({
                    "source_id": edge.get("source", edge.get("from", "")),
                    "target_id": edge.get("target", edge.get("to", "")),
                    "type": link_type,
                    "link_type": link_type,
                    "properties": {k: v for k, v in edge.items() if k not in ("source", "target", "from", "to", "type", "edge_type")},
                })

        stage_warnings = []
        if not stage_objects and not stage_links:
            stage_warnings.append(f"Stage '{stage_def.title}' produced no candidates")

        stages.append(BuildPlanStage(
            stage_id=stage_def.stage_id,
            title=stage_def.title,
            description=stage_def.description,
            order=stage_def.order,
            object_types=stage_def.object_types,
            link_types=stage_def.link_types,
            candidate_objects=stage_objects,
            candidate_links=stage_links,
            validation_warnings=stage_warnings,
        ))

    # Cross-source validation
    cross_errors = []
    cross_warnings = []

    # Check for duplicate IDs
    all_ids = [obj["id"] for stage in stages for obj in stage.candidate_objects]
    seen = set()
    for oid in all_ids:
        if oid in seen:
            cross_errors.append(f"Duplicate object ID: {oid}")
        seen.add(oid)

    # Check link references
    object_ids = set(all_ids)
    for stage in stages:
        for link in stage.candidate_links:
            if link["source_id"] not in object_ids:
                cross_errors.append(f"Link references missing source: {link['source_id']}")
            if link["target_id"] not in object_ids:
                cross_errors.append(f"Link references missing target: {link['target_id']}")

    total_objects = sum(len(s.candidate_objects) for s in stages)
    total_links = sum(len(s.candidate_links) for s in stages)

    plan = BuildPlan(
        id=f"bp-{uuid.uuid4().hex[:8]}",
        scenario_id=scenario.id,
        name=scenario.name,
        description=scenario.description,
        stages=stages,
        summary=BuildPlanSummary(
            sources=len(scenario.sources),
            total_candidate_objects=total_objects,
            total_candidate_links=total_links,
            total_validation_errors=len(errors) + len(cross_errors),
            total_validation_warnings=len(warnings) + len(cross_warnings),
        ),
        validation=BuildPlanValidationSummary(
            cross_source_errors=cross_errors,
            cross_source_warnings=cross_warnings,
        ),
        status="validated" if (len(errors) + len(cross_errors)) == 0 else "draft",
    )

    _build_plans[plan.id] = plan
    return plan
