import React, { useEffect, useState } from 'react';
import { Card, Row, Col, Table, Tag, Space, Typography, Spin, Collapse, Descriptions, Badge, Tabs, Statistic, Button, Alert } from 'antd';
import {
  ApartmentOutlined,
  LinkOutlined,
  AlertOutlined,
  ThunderboltOutlined,
  SafetyOutlined,
  CodeOutlined,
  ReloadOutlined,
  InfoCircleOutlined,
} from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { useSearchParams } from 'react-router-dom';
import { api } from '../providers/dataProvider';

const OBJECT_TYPE_EXPLANATIONS = {
  PetFoodProduct: { en: 'The central entity representing a specific pet food product. Modeled as an object because it carries unique properties (brand, species, life stage, nutrition), connects to multiple other entities, and is the primary target of rule evaluation.', zh: '代表特定宠物食品的核心实体。被建模为对象是因为它具有唯一属性（品牌、物种、生命阶段、营养），连接多个其他实体，并且是规则评估的主要目标。' },
  Brand: { en: 'Represents a manufacturer or brand. Modeled as an object to track brand-level patterns across products and enable brand-based filtering.', zh: '代表制造商或品牌。被建模为对象以跟踪品牌级别的产品模式并支持基于品牌的筛选。' },
  Ingredient: { en: 'Represents a raw material or nutritional component. Modeled as an object because ingredients have their own properties (allergen flags, risk tags) and connect to risk rules.', zh: '代表原材料或营养成分。被建模为对象是因为成分具有自己的属性（过敏原标记、风险标签）并与风险规则关联。' },
  RiskRule: { en: 'Represents a domain rule that evaluates product safety. Modeled as an object to make rules inspectable, traceable, and explainable.', zh: '代表评估产品安全性的领域规则。被建模为对象以使规则可检查、可追溯和可解释。' },
  Species: { en: 'Represents an animal species (cat, dog). Modeled as an object because species determines which rules and products are relevant.', zh: '代表动物物种（猫、犬）。被建模为对象是因为物种决定了哪些规则和产品是相关的。' },
  LifeStage: { en: 'Represents a life stage (kitten, adult, senior). Modeled as an object because nutritional requirements vary by life stage.', zh: '代表生命阶段（幼猫、成年、老年）。被建模为对象是因为营养需求因生命阶段而异。' },
};

const LINK_TYPE_EXPLANATIONS = {
  MADE_BY: { en: 'Connects a product to its brand. Essential for tracing product origin and brand-level risk patterns.', zh: '将产品与其品牌关联。对于追溯产品来源和品牌级风险模式至关重要。' },
  CONTAINS: { en: 'Connects a product to its ingredients. The foundation for rule evaluation — rules check ingredient properties to determine risk.', zh: '将产品与其成分关联。这是规则评估的基础——规则检查成分属性以确定风险。' },
  TRIGGERS_RISK: { en: 'Generated by the rule engine when a product violates a risk rule. This edge is the output of automated reasoning, not manual input.', zh: '当产品违反风险规则时由规则引擎生成。此边是自动推理的输出，而非手动输入。' },
  TARGETS_SPECIES: { en: 'Connects a product to its target species. Used to filter relevant products and rules by species.', zh: '将产品与其目标物种类关联。用于按物种筛选相关产品和规则。' },
  SUITABLE_FOR: { en: 'Connects a product to a life stage. Used to check age-appropriate nutrition.', zh: '将产品与生命阶段关联。用于检查年龄适当的营养。' },
};

const RULE_EXPLANATIONS = {
  R001: { en: 'Inputs: product fat content. Logic: if fat > 15%, generate TRIGGERS_RISK edge. Output: high_fat risk. Evidence: nutrition panel data.', zh: '输入：产品脂肪含量。逻辑：如果脂肪 > 15%，生成 TRIGGERS_RISK 边。输出：高脂肪风险。证据：营养成分表数据。' },
  R002: { en: 'Inputs: species, taurine ingredient presence. Logic: if species is cat and no taurine found, generate TRIGGERS_RISK edge. Output: missing_taurine risk.', zh: '输入：物种、牛磺酸成分是否存在。逻辑：如果是猫且未发现牛磺酸，生成 TRIGGERS_RISK 边。输出：缺少牛磺酸风险。' },
  R003: { en: 'Inputs: species, chicken ingredient presence. Logic: if species is sensitive and product contains chicken, generate TRIGGERS_RISK edge. Output: allergen risk.', zh: '输入：物种、鸡肉成分是否存在。逻辑：如果物种敏感且产品含鸡肉，生成 TRIGGERS_RISK 边。输出：过敏原风险。' },
  R004: { en: 'Inputs: species, life stage, phosphorus level. Logic: if senior cat and phosphorus > threshold, generate TRIGGERS_RISK edge.', zh: '输入：物种、生命阶段、磷含量。逻辑：如果是老年猫且磷超过阈值，生成 TRIGGERS_RISK 边。' },
  R005: { en: 'Inputs: species, life stage, protein level. Logic: if kitten and protein < minimum, generate TRIGGERS_RISK edge.', zh: '输入：物种、生命阶段、蛋白质含量。逻辑：如果是幼猫且蛋白质低于最低值，生成 TRIGGERS_RISK 边。' },
};

const { Title, Text, Paragraph } = Typography;

const SEVERITY_COLORS = {
  critical: 'red',
  high: 'orange',
  medium: 'gold',
  low: 'blue',
  info: 'default',
};

export default function SchemaPage() {
  const { t, i18n } = useTranslation();
  const [searchParams] = useSearchParams();
  const defaultTab = searchParams.get('tab') || 'objectTypes';
  const [schema, setSchema] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const loadSchema = async () => {
    setLoading(true);
    setError(false);
    try {
      const { data } = await api.get('/ontology/pet_food/schema');
      setSchema(data);
    } catch {
      setSchema(null);
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { loadSchema(); }, []);

  if (loading) {
    return <div style={{ textAlign: 'center', padding: 60 }}><Spin size="large" /></div>;
  }

  if (!schema) {
    return (
      <div style={{ textAlign: 'center', padding: 60 }}>
        <Text type="secondary" style={{ display: 'block', marginBottom: 16 }}>{error ? t('common.loadFailed') : t('schema.notAvailable')}</Text>
        {error && <Button icon={<ReloadOutlined />} onClick={loadSchema}>{t('common.retry')}</Button>}
      </div>
    );
  }

  // API returns camelCase keys with dict format; convert to arrays for tables
  const objectTypes = Object.entries(schema.objectTypes || {}).map(([name, v]) => ({
    name,
    description: v.description || '',
    properties: Array.isArray(v.properties)
      ? Object.fromEntries(v.properties.map(p => [p, { type: 'string', required: false, description: '' }]))
      : v.properties || {},
  }));
  const linkTypes = Object.entries(schema.linkTypes || {}).map(([name, v]) => ({
    name,
    source: v.from || v.source || '',
    target: v.to || v.target || '',
    description: v.description || '',
  }));
  const rules = Object.entries(schema.rules || {}).map(([key, v]) => ({
    rule_id: v.rule_id || key,
    name: v.name || key,
    severity: v.severity || 'info',
    condition_type: v.condition?.type || '',
    description: v.explanation || v.description || '',
  }));
  const actions = Object.entries(schema.actionTypes || schema.actions || {}).map(([name, v]) => ({
    name,
    description: v.description || '',
  }));

  const tabItems = [
    {
      key: 'objectTypes',
      label: <span><ApartmentOutlined /> {t('schema.objectTypes')} ({objectTypes.length})</span>,
      children: (
        <Collapse
          items={objectTypes.map(ot => ({
            key: ot.name,
            label: (
              <Space>
                <Tag color="blue">{ot.name}</Tag>
                <Text type="secondary">{ot.description}</Text>
              </Space>
            ),
            children: (
              <Space orientation="vertical" size={12} style={{ width: '100%' }}>
                {OBJECT_TYPE_EXPLANATIONS[ot.name] && (
                  <Alert
                    type="info"
                    showIcon
                    icon={<InfoCircleOutlined />}
                    title={t('schema.objectTypeExplanation')}
                    description={OBJECT_TYPE_EXPLANATIONS[ot.name][i18n.language] || OBJECT_TYPE_EXPLANATIONS[ot.name].en}
                    style={{ fontSize: 12 }}
                  />
                )}
                {ot.properties && (
                  <Table
                    dataSource={Object.entries(ot.properties).map(([k, v]) => ({ key: k, name: k, ...v }))}
                    columns={[
                      { title: t('common.name'), dataIndex: 'name', key: 'name' },
                      { title: t('common.type'), dataIndex: 'type', key: 'type' },
                      { title: t('schema.required'), dataIndex: 'required', key: 'required', render: v => v ? <Tag color="red">{t('common.yes')}</Tag> : <Tag>{t('common.no')}</Tag> },
                      { title: t('common.description'), dataIndex: 'description', key: 'description' },
                    ]}
                    size="small"
                    pagination={false}
                  />
                )}
              </Space>
            ),
          }))}
        />
      ),
    },
    {
      key: 'linkTypes',
      label: <span><LinkOutlined /> {t('schema.linkTypes')} ({linkTypes.length})</span>,
      children: (
        <Table
          dataSource={linkTypes}
          rowKey="name"
          size="small"
          pagination={false}
          columns={[
            { title: t('common.name'), dataIndex: 'name', key: 'name', render: (n) => <Tag color="green">{n}</Tag> },
            { title: t('common.source'), dataIndex: 'source', key: 'source' },
            { title: t('common.target'), dataIndex: 'target', key: 'target' },
            { title: t('common.description'), dataIndex: 'description', key: 'description' },
          ]}
          expandable={{
            expandedRowRender: (record) => {
              const exp = LINK_TYPE_EXPLANATIONS[record.name];
              return exp ? (
                <Alert type="info" showIcon icon={<InfoCircleOutlined />}
                  title={t('schema.linkTypeExplanation')}
                  description={exp[i18n.language] || exp.en}
                  style={{ fontSize: 12 }}
                />
              ) : <Text type="secondary">{record.description}</Text>;
            },
            rowExpandable: (record) => !!LINK_TYPE_EXPLANATIONS[record.name],
          }}
        />
      ),
    },
    {
      key: 'rules',
      label: <span><AlertOutlined /> {t('schema.rules')} ({rules.length})</span>,
      children: (
        <Table
          dataSource={rules}
          rowKey="rule_id"
          size="small"
          pagination={false}
          columns={[
            { title: 'ID', dataIndex: 'rule_id', key: 'rule_id', render: (id) => <Text code>{id}</Text> },
            { title: t('common.name'), dataIndex: 'name', key: 'name' },
            {
              title: t('common.severity'), dataIndex: 'severity', key: 'severity',
              render: (s) => <Tag color={SEVERITY_COLORS[s] || 'default'}>{t(`common.statusLabels.${s}`, s)}</Tag>,
            },
            { title: t('common.condition'), dataIndex: 'condition_type', key: 'condition_type' },
            { title: t('common.description'), dataIndex: 'description', key: 'description', ellipsis: true },
          ]}
          expandable={{
            expandedRowRender: (record) => {
              const exp = RULE_EXPLANATIONS[record.rule_id];
              return exp ? (
                <Alert type="info" showIcon icon={<InfoCircleOutlined />}
                  title={t('schema.ruleExplanation')}
                  description={exp[i18n.language] || exp.en}
                  style={{ fontSize: 12 }}
                />
              ) : <Text type="secondary">{record.description}</Text>;
            },
            rowExpandable: (record) => !!RULE_EXPLANATIONS[record.rule_id],
          }}
        />
      ),
    },
    ...(actions.length > 0 ? [{
      key: 'actions',
      label: <span><ThunderboltOutlined /> {t('schema.actions')} ({actions.length})</span>,
      children: (
        <Table
          dataSource={actions}
          rowKey="name"
          size="small"
          pagination={false}
          columns={[
            { title: t('common.name'), dataIndex: 'name', key: 'name', render: (n) => <Tag color="orange">{n}</Tag> },
            { title: t('common.description'), dataIndex: 'description', key: 'description' },
          ]}
        />
      ),
    }] : []),
    {
      key: 'json',
      label: <span><CodeOutlined /> {t('schema.schemaJson')}</span>,
      children: (
        <pre style={{
          background: 'rgba(255,255,255,0.04)',
          border: '1px solid rgba(255,255,255,0.08)',
          borderRadius: 8,
          padding: 16,
          fontSize: 12,
          lineHeight: 1.6,
          overflow: 'auto',
          maxHeight: 500,
        }}>
          {JSON.stringify(schema, null, 2)}
        </pre>
      ),
    },
  ];

  return (
    <Space orientation="vertical" size={20} style={{ width: '100%' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <Title level={3} style={{ margin: 0 }}>{t('schema.title')}</Title>
          <Text type="secondary">{t('schema.subtitle')}</Text>
        </div>
        <Button icon={<ReloadOutlined />} onClick={loadSchema}>{t('common.refresh')}</Button>
      </div>

      {/* Schema vs Instance explanation */}
      <Alert type="info" showIcon icon={<InfoCircleOutlined />} message={t('pipeline.schemaExplanation')} style={{ fontSize: 12 }} />

      {/* Summary stats */}
      <Row gutter={[16, 16]}>
        {[
          { title: t('schema.objectTypes'), value: objectTypes.length, icon: <ApartmentOutlined />, color: '#1677ff' },
          { title: t('schema.linkTypes'), value: linkTypes.length, icon: <LinkOutlined />, color: '#52c41a' },
          { title: t('schema.rules'), value: rules.length, icon: <AlertOutlined />, color: '#ff4d4f' },
          { title: t('schema.actions'), value: actions.length, icon: <ThunderboltOutlined />, color: '#fa8c16' },
        ].map((s, i) => (
          <Col xs={12} sm={6} key={i}>
            <Card size="small" hoverable>
              <Statistic
                title={s.title}
                value={s.value}
                prefix={React.cloneElement(s.icon, { style: { color: s.color } })}
              />
            </Card>
          </Col>
        ))}
      </Row>

      {/* Tabbed content */}
      <Card styles={{ body: { padding: '0 16px 16px' } }}>
        <Tabs
          defaultActiveKey={defaultTab}
          items={tabItems}
          style={{ marginTop: 8 }}
        />
      </Card>
    </Space>
  );
}
